-- AlterTable
ALTER TABLE "Attendance" ALTER COLUMN "clockIn" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "clockOut" DROP NOT NULL,
ALTER COLUMN "pointOut" DROP NOT NULL,
ALTER COLUMN "imgOut" DROP NOT NULL;
